### PR TITLE
Small fix for sample data

### PR DESCRIPTION
**Pull request by rlphillips**
Fixed the header in the CSV sample data file

### CODE REVIEW

**Comment by geekplux** [comment]
thanks your PR, but I have changed `key` to `label` before at https://github.com/d3-node/d3node-piechart/blob/master/index.js#L59-L64

**Comment by geekplux** [comment]
@bradoyler may you need to publish the new version to fix this.

**Comment by bradoyler** [comment]
pubbed 0.0.6 
@rlphillips try `npm i d3node-piechart@latest`

**Comment by geekplux** [comment]
@bradoyler nice action, thanks

**Pull request closed without merging**
